version: "3"
services:

  redis-docker:
    image: redis:latest
    command: redis-server --port 6379
    container_name: "docker-redis"
    labels:
      - "name=redis"
      - "mode=standalone"
#    volumes:
#      - /Users/yjshin/Database-docker/data/redis:/data
    ports:
      - 6379:6379
